"""Registry for baseline methods."""

from typing import Dict

from .base import BaselineSpec, render_baseline


BASELINES: Dict[str, BaselineSpec] = {
    "gcg": BaselineSpec(
        name="gcg",
        display_name="GCG",
        family="optimization",
        paper_title="Universal and Transferable Adversarial Attacks on Aligned Language Models",
        paper_reference="Zou et al., arXiv 2023",
        paper_url="https://arxiv.org/abs/2307.15043",
        code_url="https://github.com/llm-attacks/llm-attacks",
        description="Gradient-based search for adversarial suffixes.",
    ),
    "ffa": BaselineSpec(
        name="ffa",
        display_name="FFA",
        family="fallacy",
        paper_title="Large Language Models Are Involuntary Truth-Tellers: Exploiting Fallacy Failure for Jailbreak Attacks",
        paper_reference="Zhou et al., EMNLP 2024",
        venue="EMNLP 2024",
        paper_url="https://aclanthology.org/2024.emnlp-main.738/",
        code_url="https://github.com/Yue-LLM-Pit/FFA",
        description="Uses fallacious framing to make the model produce content it treats as deceptively false.",
        implementation_status="migrated_prompt_renderer",
        renderer_module="Baselines.ffa.renderer",
    ),
    "jailbroken": BaselineSpec(
        name="jailbroken",
        display_name="Jailbroken",
        family="prompting",
        paper_title="Jailbroken: How Does LLM Safety Training Fail?",
        paper_reference="Wei et al., NeurIPS 2023",
        venue="NeurIPS 2023",
        paper_url="https://arxiv.org/abs/2307.02483",
        description="Hand-written jailbreak prompt templates and failure modes.",
    ),
    "autodan": BaselineSpec(
        name="autodan",
        display_name="AutoDAN",
        family="optimization",
        paper_title="AutoDAN: Generating Stealthy Jailbreak Prompts on Aligned Large Language Models",
        paper_reference="Liu et al., ICLR 2024",
        venue="ICLR 2024",
        paper_url="https://openreview.net/forum?id=7Jwpw4qKkb",
        code_url="https://github.com/SheltonLiu-N/AutoDAN",
        description="Genetic search over stealthy jailbreak prefixes.",
    ),
    "artprompt": BaselineSpec(
        name="artprompt",
        display_name="ArtPrompt",
        family="obfuscation",
        paper_title="ArtPrompt: ASCII Art-based Jailbreak Attacks against Aligned LLMs",
        paper_reference="Jiang et al., ACL 2024",
        venue="ACL 2024",
        paper_url="https://aclanthology.org/2024.acl-long.809/",
        code_url="https://github.com/uw-nsl/ArtPrompt",
        description="Uses ASCII-art word rendering to hide sensitive tokens.",
    ),
    "drattack": BaselineSpec(
        name="drattack",
        display_name="DrAttack",
        family="decomposition",
        paper_title="Prompt Decomposition and Reconstruction Makes Powerful LLM Jailbreakers",
        paper_reference="Li et al., Findings of EMNLP 2024",
        venue="Findings of EMNLP 2024",
        paper_url="https://aclanthology.org/2024.findings-emnlp.813/",
        code_url="https://github.com/xirui-li/DrAttack",
        description="Decomposes and reconstructs prompts to reduce direct harmful surface form.",
    ),
    "dra": BaselineSpec(
        name="dra",
        display_name="DRA",
        family="disguise_reconstruction",
        paper_title="Making Them Ask and Answer: Jailbreaking Large Language Models in Few Queries via Disguise and Reconstruction",
        paper_reference="Liu et al., USENIX Security 2024",
        venue="USENIX Security 2024",
        paper_url="https://www.usenix.org/conference/usenixsecurity24/presentation/liu-tong",
        code_url="https://github.com/LLM-DRA/DRA",
        description="Disguises the request and asks the model to reconstruct the original task in context.",
    ),
    "cipher": BaselineSpec(
        name="cipher",
        display_name="CipherChat",
        family="encoding",
        paper_title="GPT-4 Is Too Smart To Be Safe: Stealthy Chat with LLMs via Cipher",
        paper_reference="Yuan et al., ICLR 2024",
        venue="ICLR 2024",
        paper_url="https://openreview.net/forum?id=MbfAK4s61A",
        code_url="https://github.com/RobustNLP/CipherChat",
        description="Uses ciphered communication such as Caesar/Base64-style encodings to test alignment generalization.",
    ),
    "hapla": BaselineSpec(
        name="hapla",
        display_name="HaPLa",
        family="laundering",
        paper_title="Harmful Prompt Laundering: Jailbreaking LLMs with Abductive Styles and Symbolic Encoding",
        paper_reference="Joo, Koh, and Jung, EMNLP 2025",
        venue="EMNLP 2025",
        paper_url="https://aclanthology.org/2025.emnlp-main.1296/",
        description="Launders harmful prompts through abductive writing styles and symbolic encodings.",
    ),
    "wordgame": BaselineSpec(
        name="wordgame",
        display_name="WordGame",
        family="obfuscation",
        paper_title="WordGame: Efficient & Effective LLM Jailbreak via Simultaneous Obfuscation in Query and Response",
        paper_reference="Zhang et al., NAACL Findings 2025",
        venue="NAACL Findings 2025",
        paper_url="https://aclanthology.org/2025.findings-naacl.269/",
        description="Turns the request and expected response into a word puzzle.",
    ),
    "flipattack": BaselineSpec(
        name="flipattack",
        display_name="FlipAttack",
        family="obfuscation",
        paper_title="FlipAttack: Jailbreak LLMs via Flipping",
        paper_reference="Liu et al., ICML 2025",
        venue="ICML 2025",
        paper_url="https://openreview.net/forum?id=IQ4V1yRCJv",
        code_url="https://github.com/yueliu1999/FlipAttack",
        description="Flips prompt text order to hide the original request from surface filters.",
        implementation_status="migrated_prompt_renderer",
        renderer_module="Baselines.flipattack.renderer",
    ),
    "jail_con": BaselineSpec(
        name="jail_con",
        display_name="JAIL-CON",
        family="task_concurrency",
        paper_title="Adjacent Words, Divergent Intents: Jailbreaking Large Language Models via Task Concurrency",
        paper_reference="Jiang et al., NeurIPS 2025",
        venue="NeurIPS 2025",
        paper_url="https://arxiv.org/abs/2510.21189",
        code_url="https://github.com/TrustAIRLab/JAIL-CON",
        description="Interleaves adjacent words from divergent tasks to create task concurrency.",
        implementation_status="migrated_prompt_renderer",
        renderer_module="Baselines.jail_con.renderer",
    ),
    "bijection": BaselineSpec(
        name="bijection",
        display_name="Bijection",
        family="encoding",
        paper_title="Endless Jailbreaks with Bijection Learning",
        paper_reference="Huang, Li, and Tang, ICLR 2025",
        venue="ICLR 2025",
        paper_url="https://openreview.net/forum?id=xP1radUi32",
        code_url="https://github.com/haizelabs/bijection-learning",
        description="Teaches a bijective encoding in context, then asks the model to decode and answer.",
    ),
    "llm_past_tense": BaselineSpec(
        name="llm_past_tense",
        display_name="LLM-Past-Tense",
        family="reformulation",
        paper_title="Does Refusal Training in LLMs Generalize to the Past Tense?",
        paper_reference="Andriushchenko and Flammarion, ICLR 2025",
        venue="ICLR 2025",
        paper_url="https://openreview.net/forum?id=aJUuere4fM",
        code_url="https://github.com/tml-epfl/llm-past-tense",
        description="Reformulates harmful requests as past-tense/historical questions.",
        implementation_status="migrated_prompt_renderer",
        renderer_module="Baselines.llm_past_tense.renderer",
    ),
}


def baseline_metadata() -> Dict:
    return {name: spec.to_dict() for name, spec in BASELINES.items()}


def render_registered_baseline(name: str, query: str, **kwargs) -> Dict:
    if name not in BASELINES:
        raise KeyError(f"Unknown baseline: {name}")
    return render_baseline(BASELINES[name], query, **kwargs)
